### submit an email validation request
POST https://{{host}}/api/user/sendValidationRequest
Content-Type: application/schema+json
Accept-Language: {{language}}

{
    "email": "nix@foo.org",
    "validationHash": "dfde719e-9f19-40b5-af2e-6f96d4034cda"
}

###

### submit a new event proposal
POST https://{{host}}/api/event
Content-Type: application/schema+json
Authorization: Bearer {{authToken}}
Accept-Language: {{language}}

{
  "email": "nix@foo.org",
  "title": "New event proposal with title",
  "teaser": "Teaser text for event proposal. The teaser must not  contain any html tags",
  "datetime": "2017-07-21T17:00:00",
  "event_end": "2017-07-21T19:00:00",
  "timezone": "Europe/Berlin",
  "bodytext": "Do not miss this event! It will be awesome.",
  "event_mode": "hybrid",
  "organizer_simple": "International Climate Initiative",
  "location_simple": "A cool venue",
  "location_title": "Full Name of Location",
  "location_short_title": "Short Name of Location",
  "location_description": "near you",
  "reference_id": "994432",
  "country": 13,
  "language": "de",
  "registration_link": "https://link.to.registration/",
  "streaming_link": "https://link.to.stream/",
  "is_cop_event": true
}

### delete an existing event proposal
DELETE https://{{host}}/api/event/{{id}}
Authorization: Bearer {{authToken}}
Accept-Language: {{language}}

###

### get an existing event proposal
GET https://{{host}}/api/event/{{id}}
Accept: application/json
Authorization: Bearer {{authToken}}
Accept-Language: {{language}}

### change an existing event proposal
PUT https://{{host}}/api/event/{{id}}
Content-Type: application/schema+json
Authorization: Bearer {{authToken}}
Accept-Language: {{language}}

{
    "email": "nix@foo.org",
    "title": "Update event proposal with title",
    "teaser": "Teaser text for event proposal. The teaser must not  contain any html tags",
    "datetime": "2017-07-21T17:00:00",
    "event_end": "2017-07-21T19:00:00",
    "timezone": "Europe/Berlin",
    "bodytext": "Do not miss this event! It will be awesome.",
    "event_mode": "hybrid",
    "organizer_simple": "International Climate Initiative",
    "location_simple": "A cool venue",
    "reference_id": "994432",
    "country": 13,
    "language": "de"
}

###

### Get a link to the application page
GET https://{{host}}/api/service/appPageLink/{{appPageId}}
Accept: application/json
Authorization: Bearer {{authToken}}
Accept-Language: {{language}}
