services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Cpsit\EventSubmission\:
    resource: '../Classes/*'

  Cpsit\EventSubmission\Api\Service\Settings:
    public: true

  Cpsit\EventSubmission\Api\Service\AppPageLink:
    public: true

  Cpsit\EventSubmission\Api\User\ValidationRequest:
    public: true

  Cpsit\EventSubmission\Api\Event\Withdraw:
    public: true

  Cpsit\EventSubmission\Api\Event\Put:
    public: true

  Cpsit\EventSubmission\Api\Event\Post:
    public: true

  Cpsit\EventSubmission\Api\Event\Get:
    public: true

  Cpsit\EventSubmission\Api\Event\Delete:
    public: true

  _instanceof:
    Cpsit\EventSubmission\Factory\ApiResponse\ApiResponseFactoryInterface:
      tags: [ 'EventSubmission.ApiResponseFactory' ]

    Cpsit\EventSubmission\Factory\Job\JobFactoryInterface:
      tags: [ 'EventSubmission.JobFactory' ]

    Cpsit\EventSubmission\Validator\ValidatorInterface:
      tags: [ 'EventSubmission.Validator' ]

    Cpsit\EventSubmission\Service\ServiceInterface:
      tags: [ 'EventSubmission.Service' ]

  Cpsit\EventSubmission\Factory\ApiResponse\ApiResponseFactoryFactory:
    public: true
    arguments:
      $factories: !tagged_iterator { tag: 'EventSubmission.ApiResponseFactory', index_by: 'ApiResponseFactory' }

  Cpsit\EventSubmission\Factory\Job\JobFactory:
    public: true
    arguments:
      $factories: !tagged_iterator { tag: 'EventSubmission.JobFactory', index_by: 'JobFactory' }

  Cpsit\EventSubmission\Validator\ValidatorFactoryFactory:
    public: true
    arguments:
      $factories: !tagged_iterator { tag: 'EventSubmission.Validator', index_by: 'Validator' }
